export const GET_ALL_SERVICES = "GET_ALL_SERVICES";
export const SET_ALL_SERVICES = "SET_ALL_SERVICES";
export const SET_SERVICE_SUCCESS = "SET_SERVICE_SUCCESS";
export const SET_SERVICE_FAIL = "SET_SERVICE_FAIL";
export const SET_SERVICE_LOADING = "SET_SERVICE_LOADING";
export const SET_CONNECT_SUCCESS = "SET_CONNECT_SUCCESS";
